input:
  vuls_results_path: "/home/kali/Desktop/Vuls/config/results"
  scan_interval: 360  # seconds

elasticsearch:
  hosts:
    - "https://test-api-bb4c28.es.ap-southeast-1.aws.elastic.cloud:443"
  api_key: "UnVraEdKU5SjtFQIDlrN6tS2kcnqlSvJ2ekd1UXF2ND.5c3FQ5npYZ=="
  bulk_size: 1000

logging:
  level: "INFO"
  file: "/var/log/vuls-ingest.log"
